version: '2'
services:
  web:
    build:
      context: 'nginx'
    image: local/getpass/nginx:1.15
    environment:
      - FASTCGI_PASS_HOST=php
    ports:
      - '8100:80'
    depends_on:
      - php
    volumes_from:
      - php
  php:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'php'
      args:
        - PHP_BASE_IMAGE_VERSION=${PHP_BASE_IMAGE_VERSION}
        - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG}
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    volumes:
      - ./tests:/tests:delegated
      # Framework testing
      - ./_host-volumes/yii2:/yii2:delegated
      # Application testing
      - ./_host-volumes/app:/app:delegated
      # Composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
  db:
    image: mongo:3.2.21
    volumes:
      - ./mongo/data:/data/db
